#! /bin/sh

BG_IMAGE=003.jpg

xsetroot -cursor_name arrow &
pgrep -x feh > /dev/null || feh --bg-scale $HOME/Pictures/Walls/$BG_IMAGE &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五
#bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap           15
bspc config top_padding          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a chromium desktop='^2'
bspc rule -a lxappearance state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh


