#!/bin/sh
# BSPWM Config

bspc config border_width                    2
bspc config window_gap                     10
bspc config top_padding                     5
bspc config right_padding                  10
bspc config bottom_padding                 10
bspc config left_padding                   10

bspc monitor -d I II III IV

bspc config auto_alternate                 true
bspc config auto_cancel                    true
bspc config split_ratio                    0.50
bspc config gapless_monocle                true
bspc config focus_follows_pointer          true

# Colors
bspc config normal_border_color            "#93a1a1"
bspc config active_border_color            "#eee8d5"
bspc config focused_border_color           "#eee8d5"
bspc config presel_border_color            "#a537fd"
bspc config urgent_border_color            "#a537fd"
bspc config focused_locked_border_color    "#a537fd"


# Rules
bspc rule -a Skype pseudo_tiled=on
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Thunar pseudo_tiled=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=off

